# config/zed_yaml
# Parameters for Stereolabs ZED camera
---
/**:
    ros__parameters:
        general:
            camera_model: "zed"
            camera_name: "zed" # usually overwritten by launch file

        depth:
            min_depth: 0.3 # Min: 0.3, Max: 3.0
            max_depth: 10. # Dynamic
