# config/zed2_yaml
# Parameters for Stereolabs ZED2 camera
---
/**:
    ros__parameters:
        general:
            camera_model: "zed2"
            camera_name: "zed2" # usually overwritten by launch file

        depth:
            min_depth: 0.2 # Min: 0.2, Max: 3.0
            max_depth: 10.0 # Max: 40.0

