# config/zedm_yaml
# Parameters for Stereolabs ZED mini camera
---
/**:
    ros__parameters:
        general:
            camera_model: "zedm"
            camera_name: "zedm" # usually overwritten by launch file

        depth:
            min_depth: 0.1 # Min: 0.1, Max: 3.0
            max_depth: 10.0 # Max: 20.0

