#!/bin/bash

GITHUB_REGISTRY="ghcr.io/roboeagles4828"
IMAGE_NAME="developer-environment:2023"

docker build -t $GITHUB_REGISTRY/$IMAGE_NAME --cache-from $GITHUB_REGISTRY/$IMAGE_NAME .

echo "Build finished"

echo "Would you like to run the image in interactive mode? (y/n)"
read INTERACTIVE

if [ "$INTERACTIVE" = "y" ]; then
    docker run --rm -it -e ACCEPT_EULA=y $GITHUB_REGISTRY/$IMAGE_NAME
fi

echo "Would you like to push the image to the registry? (y/n)"
read PUSH

if [ "$PUSH" = "y" ]; then
    docker push $GITHUB_REGISTRY/$IMAGE_NAME
fi