version: "3.9"
services:
  humble2204:
    image: "ghcr.io/roboeagles4828/jetson:2023"
    network_mode: "host"
    environment:
      - ROS_DOMAIN_ID=0
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 3
        window: 120s
    volumes:
    - ./:/opt/workspace
    ports:
    - "1-65535:1-65535"
  zed_cam:
    image: ghcr.io/roboeagles4828/jetson-zed:2023.1
    network_mode: "host"
    privileged: true
    ports:
    - "1-65535:1-65535"
    deploy:
      resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]
    command: ["ros2", "launch", "zed_wrapper", "zed2i.launch.py"]
