<?xml version = "1.0"?>
<robot xmlns:xacro = "http://www.ros.org/wiki/xacro">

    <xacro:property name="back_leg_length" value="0.0508" />
    <xacro:property name="back_leg_width" value="0.457" />
    <xacro:property name="back_leg_height" value="0.677" />
    <xacro:property name="lower_bearing_distance" value = ".076" />
    <xacro:property name="upper_bearing_distance" value = ".030" />
    <xacro:property name="inside_legs_distance" value = ".279" />
    <xacro:property name="each_leg_width" value = ".0254" />

    <xacro:macro name = "back_leg" params = "prefix parent *origin">
        <link name = "${prefix}_back_leg_link">
            <xacro:inertial_box mass = "1" x = "${back_leg_length}" y = "${back_leg_width}" z = "${back_leg_height}">
                <origin xyz = "0 0 ${back_leg_height/2}" rpy = "0 0 0"/>
            </xacro:inertial_box>
            <visual>
                <origin xyz = "0 -${(inside_legs_distance + (each_leg_width * 2)) / 2} 0" rpy = "${pi /2} 0 0"/>
                <geometry>
                    <mesh filename="package://edna_description/meshes/Back_Legs_V6.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name = "red"/>
            </visual>
            <collision>
                <origin xyz = "0 0 ${back_leg_height / 2}" rpy = "0 0 0"/>
                <geometry>
                    <box size = "${back_leg_length} ${back_leg_width} ${back_leg_height}"/>
                </geometry>
            </collision>
        </link>
        <joint name = "${prefix}_back_leg_joint" type = "fixed">
            <parent link = "${parent}"/>
            <child link = "${prefix}_back_leg_link"/>
            <xacro:insert_block name = "origin"/>
        </joint>
    </xacro:macro>
</robot>