<?xml version = "1.0"?>
<robot xmlns:xacro = "http://www.ros.org/wiki/xacro">

    <xacro:property name="elevator_leg_length" value="0.0508" />
    <xacro:property name="elevator_leg_width" value="0.3302" />
    <xacro:property name="elevator_leg_height" value="0.5842" />
    
    <xacro:property name="roller_bar_length" value="0.0508" />
    <xacro:property name="roller_bar_width" value="0.7112" />
    <!-- <xacro:property name="roller_bar_height" value="0.527" /> -->
    <xacro:property name="roller_bar_height" value="0.1" />
    <xacro:property name="roller_bar_wheel_radius" value="0.0254"/>

    <xacro:macro name = "elevator_leg" params = "prefix parent *origin">
        <link name = "${prefix}_elevator_leg_link">
            <xacro:inertial_box mass = "1" x = "${elevator_leg_length}" y = "${elevator_leg_width}" z = "${elevator_leg_height}">
                <origin xyz = "0 0 ${elevator_leg_height/2}" rpy = "0 0 0"/>
            </xacro:inertial_box>
            <visual>
                <origin xyz = "0 0 0" rpy = "0 0 0"/>
                <geometry>
                    <mesh filename="package://edna_description/meshes/Front_Legs_V2.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name = "red"/>
            </visual>
            <collision>
                <origin xyz = "0 0 0" rpy = "0 0 0"/>
                <geometry>
                    <box size = "${elevator_leg_length} ${elevator_leg_width} ${elevator_leg_height}"/>
                </geometry>
            </collision>
        </link>
        <joint name = "${prefix}_elevator_leg_joint" type = "fixed">
            <parent link = "${parent}"/>
            <child link = "${prefix}_elevator_leg_link"/>
            <xacro:insert_block name = "origin"/>
        </joint>


        <link name = "${prefix}_roller_bar_link">
            <xacro:inertial_box mass = "1" x = "${roller_bar_length}" y = "${roller_bar_width}" z = "${roller_bar_height}">
                <origin xyz = "0 0 ${roller_bar_height/2}" rpy = "${pi/2} 0 0"/>
            </xacro:inertial_box>
            <visual>
                <origin xyz = "0 0 -0.24" rpy = "0 0 0"/>
                <geometry>
                    <mesh filename="package://edna_description/meshes/Roller_Bar_V2.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name = "red"/>
            </visual>
            <collision>
                <origin xyz = "0 0 ${roller_bar_height/2 - 0.025}" rpy = "0 0 0"/>
                <geometry>
                    <box size = "${roller_bar_length} ${roller_bar_width} ${roller_bar_height*0.75}"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz = "0 0 0.065" rpy = "${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius = "${0.0492125/2}" length = "${roller_bar_width}"/>
                </geometry>
            </collision>
        </link>
        <joint name = "${prefix}_roller_bar_joint" type = "prismatic">
            <parent link = "${prefix}_elevator_leg_link"/>
            <child link = "${prefix}_roller_bar_link"/>
            <axis xyz = "0 0 1"/>
            <limit effort = "100.0" lower = "0" upper = "0.06985" velocity = "1"/>
            <!-- <limit effort = "100.0" lower = "0" upper = "1" velocity = "0.5"/> -->
            <origin xyz = "0 0 ${elevator_leg_height/2 + 0.01}" rpy = "0 0 0"/>
            <!-- <origin xyz = "0 0 0.37" rpy = "0 0 0"/> -->
        </joint>
    </xacro:macro>
</robot>