<?xml version = "1.0"?>
<robot xmlns:xacro = "http://www.ros.org/wiki/xacro">

    <xacro:property name="elevator_outer_length" value="0.685" />
    <xacro:property name="elevator_outer_width" value="0.025" />
    <xacro:property name="elevator_outer_height" value="0.082" />

    <xacro:property name="elevator_center_length" value="0.685"/>
    <xacro:property name="elevator_center_width" value="0.025"/>
    <xacro:property name="elevator_center_height" value="0.215"/>

    <xacro:property name="elevator_center_offset_x" value="0.05"/>
    <xacro:property name="elevator_center_offset_z" value="0.08"/>

    <xacro:property name="elevator_outer_offset_x" value="0.04"/>
    <xacro:property name="elevator_outer_offset_z" value="0.07"/>

    <xacro:include filename="$(find edna_description)/urdf/parts/elevator_leg.xacro" />

    <xacro:macro name = "elevator" params = "prefix parent *origin">
        <link name = "${prefix}_outer_1_link">
            <xacro:inertial_box mass = "1" x = "${elevator_outer_length}" y = "${elevator_outer_width}" z = "${elevator_outer_height}">
                <origin xyz = "0 0 ${elevator_outer_height/2}" rpy = "0 0 0"/>
            </xacro:inertial_box>
            <visual>
                <!-- <origin xyz = "0.254264 -0.07 -0.072" rpy = "${pi} 0 0"/> -->
                <origin xyz = "${elevator_outer_length/2 - 0.08} 0.07 0.062" rpy = "${pi} 0 0"/>
                <geometry>
                    <mesh filename="package://edna_description/meshes/elevator_outer_updated.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name = "blue"/>
            </visual>
            <visual>
                <origin xyz = "${elevator_outer_length/2 - 0.08} ${0.07+elevator_middle_distance} 0.062" rpy = "${pi} 0 0"/>
                <geometry>
                    <mesh filename="package://edna_description/meshes/elevator_outer_updated.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name = "blue"/>
            </visual>
            <collision>
                <origin xyz = "${elevator_outer_length/2 - 0.0104} -0.0025 0.023" rpy = "0 0 0"/>
                <geometry>
                    <box size = "${elevator_outer_length + 0.0004} ${elevator_outer_width + 0.0004} ${elevator_outer_height+0.002}"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz = "${elevator_outer_length/2 - 0.0104} ${-0.0025+elevator_middle_distance} 0.023" rpy = "0 0 0"/>
                <geometry>
                    <box size = "${elevator_outer_length + 0.0004} ${elevator_outer_width + 0.0004} ${elevator_outer_height+0.002}"/>
                </geometry>
            </collision>
        </link>

        <joint name = "${prefix}_outer_1_joint" type = "revolute">
            <parent link = "${parent}"/>
            <child link = "${prefix}_outer_1_link"/>
            <axis xyz = "0 -1 0"/>
            <limit effort="1000.0" lower="0.0" upper="0.548" velocity="0.5"/>
            <mimic joint = "arm_roller_bar_joint" multiplier = "1.8" offset = "0"/>
            <xacro:insert_block name = "origin"/>
        </joint> 



        <link name = "${prefix}_center_link">
            <xacro:inertial_box mass = "1" x = "${elevator_outer_length}" y = "${elevator_outer_width}" z = "${elevator_outer_height}">
                <origin xyz = "0 0 ${elevator_outer_height/2}" rpy = "0 0 0"/>
            </xacro:inertial_box>
            <visual>
                <origin xyz = "${0.265+elevator_center_offset_x} 0.004 ${-0.085+elevator_center_offset_z}" rpy = "0 0 ${pi}"/>
                <geometry>
                    <mesh filename="package://edna_description/meshes/elevator_center.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name = "blue"/>
            </visual>
            <visual>
                <origin xyz = "${0.265+elevator_center_offset_x} ${0.004+elevator_middle_distance} ${-0.085+elevator_center_offset_z}" rpy = "0 0 ${pi}"/>
                <geometry>
                    <mesh filename="package://edna_description/meshes/elevator_center.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name = "blue"/>
            </visual>
            <collision>
                <origin xyz = "${elevator_center_length/2 - 0.03} 0 0" rpy = "0 0 0"/>
                <geometry>
                    <box size = "${elevator_center_length + 0.01} ${elevator_center_width} ${elevator_center_height}"/>
                </geometry>
                <material name="ghost"/>
            </collision>
            <collision>
                <origin xyz = "${elevator_center_length/2 - 0.03} ${elevator_middle_distance} 0" rpy = "0 0 0"/>
                <geometry>
                    <box size = "${elevator_center_length + 0.01} ${elevator_center_width} ${elevator_center_height}"/>
                </geometry>
                <material name="ghost"/>
            </collision>
        </link>
        <joint name = "${prefix}_center_joint" type = "prismatic">
            <parent link = "${prefix}_outer_1_link" joint = "${prefix}_outer_1_joint"/>
            <child link = "${prefix}_center_link"/>
            <axis xyz = "1 0 0"/>
            <limit effort="1000.0" lower="0.0" upper="0.56" velocity="0.5"/>
            <origin xyz = "${0.1-elevator_center_offset_x} 0 ${elevator_center_offset_z}" rpy = "0 0 0"/>
        </joint>




        <link name = "${prefix}_outer_2_link">
            <xacro:inertial_box mass = "1" x = "${elevator_outer_length}" y = "${elevator_outer_width}" z = "${elevator_outer_height}">
                <origin xyz = "0 0 ${elevator_outer_height/2}" rpy = "0 0 0"/>
            </xacro:inertial_box>
            <visual>
                <!-- <origin xyz = "${elevator_outer_offset_x+0.34} -0.07 ${-1*(elevator_outer_offset_z+0.015)}" rpy = "0 0 ${pi}"/> -->
                 <origin xyz = "${elevator_outer_length/2 + 0.045} 0.075 -0.06" rpy = "0 0 ${pi}"/>
                <geometry>
                    <mesh filename="package://edna_description/meshes/elevator_outer_updated.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name = "blue"/> 
            </visual>
            <visual>
                <!-- <origin xyz = "${elevator_outer_offset_x+0.34} -0.07 ${-1*(elevator_outer_offset_z+0.015)}" rpy = "0 0 ${pi}"/> -->
                 <origin xyz = "${elevator_outer_length/2 + 0.045} ${0.075+elevator_middle_distance} -0.06" rpy = "0 0 ${pi}"/>
                <geometry>
                    <mesh filename="package://edna_description/meshes/elevator_outer_updated.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name = "blue"/> 
            </visual>
            <collision>
                <origin xyz = "${elevator_outer_length/2 - 0.025} 0 0" rpy = "0 0 ${pi}"/>
                <geometry>
                    <box size = "${elevator_outer_length + 0.025} ${elevator_outer_width} ${elevator_outer_height}"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz = "${elevator_outer_length/2 - 0.025} ${elevator_middle_distance} 0" rpy = "0 0 ${pi}"/>
                <geometry>
                    <box size = "${elevator_outer_length + 0.025} ${elevator_outer_width} ${elevator_outer_height}"/>
                </geometry>
            </collision>
        </link>
        <joint name = "${prefix}_outer_2_joint" type = "prismatic">
            <axis xyz = "1 0 0"/>
            <limit effort="1000.0" lower="0.0" upper="0.568" velocity="0.5"/>
            <parent link = "${prefix}_center_link"/>
            <child link = "${prefix}_outer_2_link"/>
            <mimic joint = "${prefix}_center_joint" multiplier = "1" offset = "0"/>
            <origin xyz = "${elevator_outer_offset_x} 0 ${elevator_outer_offset_z}" rpy = "0 0 0"/>
        </joint>
    </xacro:macro>
</robot>