<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="intake_block_height" value="0.0508" />
    <xacro:property name="intake_block_length" value="0.449834" />
    <xacro:property name="intake_block_width" value="0.4064" />

  <xacro:macro name="intake" params="prefix parent *origin">
    <link name = "${prefix}_intake_link">
        <xacro:inertial_box mass = "1" x = "${intake_block_length}" y = "${intake_block_length}" z = "${intake_block_height}">
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
        </xacro:inertial_box>
        <visual>
            <origin xyz = "${intake_block_length-0.04} ${intake_block_width/2} -0.0508" rpy = "${pi/2} 0 0"/>
            <geometry>
                <mesh filename = "package://edna_description/meshes/Front_Intake_V2.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name = "blue"/>
        </visual>
        <collision>
            <origin xyz = "${intake_block_length/2 - 0.03} 0 0" rpy = "0 0 0"/>
            <geometry>
                <box size="${intake_block_length} ${intake_block_width} ${intake_block_height}"/>
            </geometry>
        </collision>
    </link>

    <joint name="${prefix}_intake_joint" type="revolute">
        <xacro:insert_block name="origin" />
        <parent link="${parent}"/>
        <child link="${prefix}_intake_link"/>
        <axis xyz = "0 1 0"/>
        <limit effort = "100.0" lower = "0" upper = "${pi/2 - 0.05}" velocity = "1"/>
    </joint>

    <!-- <xacro:gripper prefix="${prefix}" parent="${prefix}_intake_link">
        <origin xyz = "${intake_block_length - 0.05} 0 -0.035" rpy = "0 0 0" />
    </xacro:gripper> -->


  </xacro:macro>
</robot>