<?xml version = "1.0"?>
<robot xmlns:xacro = "http://www.ros.org/wiki/xacro">

    <xacro:property name="roller_bar_length" value="0.052" />
    <xacro:property name="roller_bar_width" value="0.635" />
    <xacro:property name="roller_bar_height" value="0.527" />

    <xacro:macro name = "roller_bar" params = "prefix parent *origin">
        <link name = "${prefix}_link">
            <xacro:inertial_box mass = "1" x = "${roller_bar_length}" y = "${roller_bar_width}" z = "${roller_bar_height}">
                <origin xyz = "0 0 ${roller_bar_height/2}" rpy = "0 0 0"/>
            </xacro:inertial_box>
            <visual>
                <origin xyz = "0 0 ${roller_bar_height/2}" rpy = "${pi/2} 0 0"/>
                <geometry>
                    <mesh filename="package://edna_description/meshes/Roller_Bar.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name = "blue"/>
            </visual>
            <collision>
                <origin xyz = "0 0 ${roller_bar_height/2}" rpy = "0 0 0"/>
                <geometry>
                    <box size = "${roller_bar_length} ${roller_bar_width} ${roller_bar_height}"/>
                </geometry>
            </collision>
        </link>
        <joint name = "${prefix}_box_joint" type = "fixed">
            <parent link = "${parent}"/>
            <child link = "${prefix}_link"/>
            <xacro:insert_block name = "origin"/>
        </joint>
    </xacro:macro>
</robot>