<?xml version="1.0"?>

<!--
// Copyright 2022 Stereolabs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
-->

<robot xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:property name="M_PI"     value="3.1415926535897931" />

  <!--
    Parameters:
      - name: the camera's name.  should match the parameter sent to the launch file for this camera
      - model: the tye of camera, one of zed, zedm, zed2, zed2i
      - parent: the parent link of the camera.  must be defined in the URDF file that uses this macro
      - origin: the xyz/rpy offset from the parent link
  -->
  <xacro:macro name="zed_camera" params="prefix=zed model=zed parent *origin">
    <xacro:if value="${model == 'zed'}">
      <xacro:property name="baseline" value="0.12" />
      <xacro:property name="height" value="0.03" />
      <xacro:property name="bottom_slope" value="0.05" />
      <xacro:property name="screw_offset_x" value="0.0" />
      <xacro:property name="optical_offset_x" value="-0.01" />
    </xacro:if>
    <xacro:if value="${model == 'zedm'}">
      <xacro:property name="baseline" value="0.06" />
      <xacro:property name="height" value="0.0265" />
      <xacro:property name="bottom_slope" value="0.0" /> 
      <xacro:property name="screw_offset_x" value="0.0" />
      <xacro:property name="optical_offset_x" value="0.0" />
    </xacro:if>
    <xacro:if value="${model == 'zed2'}">
      <xacro:property name="baseline" value="0.12" />
      <xacro:property name="height" value="0.03" />
      <xacro:property name="bottom_slope" value="0.05" />
      <xacro:property name="screw_offset_x" value="0.0" />
      <xacro:property name="optical_offset_x" value="-0.01" />
    </xacro:if>
    <xacro:if value="${model == 'zed2i'}">
      <xacro:property name="baseline" value="0.12" />
      <xacro:property name="height" value="0.03" />
      <xacro:property name="bottom_slope" value="0.0" />
      <xacro:property name="screw_offset_x" value="-0.01" />
      <xacro:property name="optical_offset_x" value="-0.01" />
    </xacro:if>



    <!-- Camera mounting point (the threaded screw hole in the bottom) -->
    <link name="${prefix}_base_link" />
    <joint name="${prefix}_base_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${prefix}_base_link"/>
      <xacro:insert_block name="origin" />
    </joint>


    <!-- Camera Center -->
    <link name="${prefix}_camera_center">
      <visual>
        <origin xyz="${screw_offset_x} 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://edna_description/meshes/${model}.stl" />
        </geometry>
        <material name="${model}_mat" />
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://edna_description/meshes/${model}.stl" />
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}_camera_center_joint" type="fixed">
      <parent link="${prefix}_base_link"/>
      <child link="${prefix}_camera_center"/>
      <origin xyz="0 0 ${height/2}" rpy="0 ${bottom_slope} 0" />
    </joint>


    <!-- Left Camera -->
    <link name="${prefix}_left_camera_frame" />
    <joint name="${prefix}_left_camera_joint" type="fixed">
      <parent link="${prefix}_camera_center"/>
      <child link="${prefix}_left_camera_frame"/>
      <origin xyz="0 ${baseline/2} 0" rpy="0 0 0" />
    </joint>

    <link name="${prefix}_left_camera_optical_frame"/>
    <joint name="${prefix}_left_camera_optical_joint" type="fixed">
      <origin xyz="${optical_offset_x} 0 0" rpy="-${M_PI/2} 0.0 -${M_PI/2}"/>
      <parent link="${prefix}_left_camera_frame"/>
      <child link="${prefix}_left_camera_optical_frame"/>
    </joint>



    <!-- Right Camera -->
    <link name="${prefix}_right_camera_frame" />
    <joint name="${prefix}_right_camera_joint" type="fixed">
      <parent link="${prefix}_camera_center"/>
      <child link="${prefix}_right_camera_frame"/>
      <origin xyz="0 -${baseline/2} 0" rpy="0 0 0" />
    </joint>

    <link name="${prefix}_right_camera_optical_frame"/>
    <joint name="${prefix}_right_camera_optical_joint" type="fixed">
      <origin xyz="${optical_offset_x} 0 0" rpy="-${M_PI/2} 0.0 -${M_PI/2}"/>
      <parent link="${prefix}_right_camera_frame"/>
      <child link="${prefix}_right_camera_optical_frame"/>
    </joint>

    <link name="${prefix}_imu_link" />
    <joint name="${prefix}_imu_joint" type="fixed">
      <parent link="${prefix}_left_camera_frame"/>
      <child link="${prefix}_imu_link"/>
      <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>
  </xacro:macro>
</robot>
