teleop_twist_joy_node:
  ros__parameters:
    require_enable_button: false
    axis_linear:  # Left thumb stick vertical
      y: 0
      x: 1
      # z: 5
    scale_linear:
      x: 3.0
      y: 3.0
    scale_linear_turbo:
      x: 8.0
      y: 8.0

    axis_angular:  # Right thumb stick horizontal
      yaw: 3
    scale_angular:
      yaw: 5.0
    scale_angular_turbo:
      yaw: 7.0
    
    enable_turbo_button: 1
      
