<?xml version="1.0"?>
<robot name="edna" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Args -->
  <xacro:arg name="hw_interface_plugin" default="swerve_hardware/IsaacDriveHardware"/>
  <xacro:arg name="namespace" default="default"/>
  <xacro:property name="ns" value="$(arg namespace)" />

  <!-- Include Files -->
  <xacro:include filename="$(find edna_description)/urdf/control/drive.xacro" />
  <xacro:include filename="$(find edna_description)/urdf/util/macros.xacro" />
  <xacro:include filename="$(find edna_description)/urdf/util/materials.xacro" />
  <xacro:include filename="$(find edna_description)/urdf/parts/square_chassis.xacro" />
  <xacro:include filename="$(find edna_description)/urdf/parts/swerve_axle.xacro" />
  <xacro:include filename="$(find edna_description)/urdf/parts/zed_macro.urdf.xacro" />
  <xacro:include filename="$(find edna_description)/urdf/parts/elevator_leg.xacro" />
  <xacro:include filename="$(find edna_description)/urdf/parts/back_leg.xacro" />
  <xacro:include filename="$(find edna_description)/urdf/parts/lidar.xacro" />
  <xacro:include filename="$(find edna_description)/urdf/parts/elevator.xacro" />

  <!-- Axle Position Variables -->
  <xacro:property name="axle_pos" value="${301.625 / 1000}" />
  <xacro:property name="axle_pos_z" value="${69.056 / 1000}" />

  <!-- Camera Position Variables -->
  <xacro:property name="cam_pos" value="0 0 0.3"/> <!-- Made up values, replace with real ones later. -->

  <!-- X IS FORWARD -->
  <!-- Y IS LEFT -->
  <!-- Z IS UP -->

  <!-- Chassis -->
  <link name="base_link"></link>
  <xacro:square_chassis prefix="${ns}_swerve" parent="base_link">
    <origin xyz="0 0 0" rpy="0 0 0" />
  </xacro:square_chassis>

  <!-- Drive Train -->
  <xacro:swerve_axle prefix="${ns}_front_left" parent="${ns}_swerve_chassis_link">
    <origin xyz="${axle_pos} ${axle_pos} ${axle_pos_z}" rpy="0 0 0" />
  </xacro:swerve_axle>
  <xacro:swerve_axle prefix="${ns}_front_right" parent="${ns}_swerve_chassis_link">
    <origin xyz="${axle_pos} -${axle_pos} ${axle_pos_z}" rpy="0 0 0" />
  </xacro:swerve_axle>
  <xacro:swerve_axle prefix="${ns}_rear_left" parent="${ns}_swerve_chassis_link">
    <origin xyz="-${axle_pos} ${axle_pos} ${axle_pos_z} " rpy="0 0 0" />
  </xacro:swerve_axle>
  <xacro:swerve_axle prefix="${ns}_rear_right" parent="${ns}_swerve_chassis_link">
    <origin xyz="-${axle_pos} -${axle_pos} ${axle_pos_z}" rpy="0 0 0" />
  </xacro:swerve_axle>
  
  <!-- Sensors -->
  <xacro:zed_camera prefix="${ns}_zed" model="zed2i" parent="${ns}_swerve_chassis_link">
    <origin xyz="${cam_pos}" rpy="0 0 0" />
  </xacro:zed_camera> 

  <xacro:elevator_leg prefix="${ns}_arm" parent="${ns}_swerve_chassis_link">
    <origin xyz = "-0.1905 0 ${0.527/2 + 0.03}" rpy = "0 0 ${pi}"/>
    <origin xyz = "0 0 ${0.527/5 + 0.01}" rpy = "${pi/2} 0 0"/>
  </xacro:elevator_leg>

  <xacro:back_leg prefix="${ns}_arm" parent="${ns}_swerve_chassis_link">
    <origin xyz = "${0.7366/2 - 0.0508/2} 0 ${back_leg_height/2 + 0.05588}" rpy = "0 0 ${pi}" />
  </xacro:back_leg>

  <!--Right Elevator-->
  <xacro:elevator prefix="${ns}_elevator_right" parent="${ns}_arm_back_leg_link" ns="${ns}">
    <origin xyz = "0.00253 -0.152 0.3738731" rpy = "${pi} ${(0.0174533*16.3)} 0" />
  </xacro:elevator>

  <!--Left Elevator-->
  <xacro:elevator prefix="${ns}_elevator_left" parent="${ns}_arm_back_leg_link" ns="${ns}">
    <origin xyz = "0.00253 0.28 0.3738731" rpy = "${pi} ${(0.0174533*16.3)} 0" />
  </xacro:elevator>

  <xacro:lidar prefix="${ns}_lidar" parent="${ns}_swerve_chassis_link" radius="0.035" length="0.025">
    <origin xyz="0 0 .035" rpy="0 0 0" />
  </xacro:lidar>

  <xacro:swerve_drive_control plugin="$(arg hw_interface_plugin)" ns="${ns}"/>
</robot>