#!/bin/bash

GITHUB_REGISTRY="ghcr.io/roboeagles4828"
IMAGE_NAME="developer-isaac-ros"
IMAGE_TAG="1"

docker build -t "$GITHUB_REGISTRY/$IMAGE_NAME:$IMAGE_TAG" \
    --build-arg HAS_GPU="true" \
    --network host \
    --cache-from "$GITHUB_REGISTRY/$IMAGE_NAME:$IMAGE_TAG" \
    --cache-from "$GITHUB_REGISTRY/$IMAGE_NAME:latest" .

echo "Build finished"

echo "Would you like to run the image in interactive mode? (y/n)"
read INTERACTIVE

if [ "$INTERACTIVE" = "y" ]; then
    docker run --rm -it \
    --privileged \
    --network host \
    --runtime nvidia \
    -e NVIDIA_VISIBLE_DEVICES=all \
    -e NVIDIA_DRIVER_CAPABILITIES=all \
    -e ACCEPT_EULA=y "$GITHUB_REGISTRY/$IMAGE_NAME:$IMAGE_TAG" /bin/bash
fi

echo "Would you like to push the image to the registry? (y/n)"
read PUSH

if [ "$PUSH" = "y" ]; then
    docker tag "$GITHUB_REGISTRY/$IMAGE_NAME:$IMAGE_TAG" "$GITHUB_REGISTRY/$IMAGE_NAME:latest"
    docker push "$GITHUB_REGISTRY/$IMAGE_NAME:$IMAGE_TAG"
    docker push "$GITHUB_REGISTRY/$IMAGE_NAME:latest"
fi