#!/bin/bash
# Followed basic instructions from isaac ros github

# Source ros2
source /opt/ros/${ROS_DISTRO}/setup.bash
# Create workspace
mkdir -p  ~/workspaces/isaac_ros-dev/src

# Deps
cd ~/workspaces/isaac_ros-dev/src && \
    git clone https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nitros && \
    git clone https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline && \
    git clone https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference && \
    git clone https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common && \
    git clone https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_visual_slam && \
    git clone https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_pose_estimation && \
    git clone https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_apriltag && \
    git clone https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_compression    

# Build and test
cd ~/workspaces/isaac_ros-dev && colcon build --symlink-install

source install/setup.bash && colcon test --executor sequential