/*:
  controller_manager:
    ros__parameters:
      update_rate: 10  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      swerve_controller:
        type: swerve_controller/SwerveController

      joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController

  swerve_controller:
    ros__parameters:
      #Used to scale velocity
      chassis_length_meters: 0.6032
      chassis_width_meters: 0.6032
      wheel_radius_meters: 0.0508
      max_wheel_angular_velocity: 65.0
      #If no new twist commands are created in 1 second the robot will halt 
      cmd_vel_timeout_seconds: 1.0
      use_stamped_vel: false
      front_left_wheel_joint: front_left_wheel_joint
      front_right_wheel_joint: front_right_wheel_joint
      rear_left_wheel_joint: rear_left_wheel_joint
      rear_right_wheel_joint: rear_right_wheel_joint
      front_left_axle_joint: front_left_axle_joint
      front_right_axle_joint: front_right_axle_joint
      rear_left_axle_joint: rear_left_axle_joint
      rear_right_axle_joint: rear_right_axle_joint
      linear:
        x:
          has_velocity_limits: {
            type: bool,
            default_value: true,
          }
          has_acceleration_limits: {
            type: bool,
            default_value: true,
          }
          has_jerk_limits: {
            type: bool,
            default_value: true,
          }
          max_velocity: {
            type: double,
            default_value: 31.4,
          }
          min_velocity: {
            type: double,
            default_value: -31.4,
          }
          max_acceleration: {
            type: double,
            default_value: 10.0,
          }
          min_acceleration: {
            type: double,
            default_value: -10.0,
          }
          max_jerk: {
            type: double,
            default_value: 1.0,
          }
          min_jerk: {
            type: double,
            default_value: -1.0,
          }
      


  joint_trajectory_controller:
    ros__parameters:
      joints:
        - 'arm_roller_bar_joint'
        - 'elevator_center_joint'
        - 'elevator_outer_1_joint'
        - 'elevator_outer_2_joint'
        - 'top_gripper_right_arm_joint'
        - 'top_gripper_left_arm_joint'
        - 'top_slider_joint'
        - 'bottom_intake_joint'
        - 'bottom_gripper_right_arm_joint'
        - 'bottom_gripper_left_arm_joint'

      command_interfaces:
        - position

      state_interfaces:
        - position
        - velocity

      state_publish_rate: 50.0
      action_monitor_rate: 20.0

      allow_partial_joints_goal: false
      open_loop_control: true
      constraints:
        stopped_velocity_tolerance: 0.01
        goal_time: 0.0

