/*:
  controller_manager:
    ros__parameters:
      update_rate: 20  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      swerve_controller:
        type: swerve_controller/SwerveController

      forward_position_controller:
        type: position_controllers/JointGroupPositionController
      
      forward_velocity_controller:
        type: velocity_controllers/JointGroupVelocityController

      joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController

  swerve_controller:
    ros__parameters:
      #Used to scale velocity
      chassis_length_meters: 0.6032
      chassis_width_meters: 0.6032
      wheel_radius_meters: 0.0508
      max_wheel_angular_velocity: 100.0
      #If no new twist commands are created in 1 second the robot will halt 
      cmd_vel_timeout_seconds: 1.0
      use_stamped_vel: false
      front_left_wheel_joint: front_left_wheel_joint
      front_right_wheel_joint: front_right_wheel_joint
      rear_left_wheel_joint: rear_left_wheel_joint
      rear_right_wheel_joint: rear_right_wheel_joint
      front_left_axle_joint: front_left_axle_joint
      front_right_axle_joint: front_right_axle_joint
      rear_left_axle_joint: rear_left_axle_joint
      rear_right_axle_joint: rear_right_axle_joint
      
      linear.x.has_velocity_limits: false
      linear.x.has_acceleration_limits: true
      linear.x.has_jerk_limits: false
      linear.x.max_velocity: 2.0
      linear.x.min_velocity: -2.0
      linear.x.max_acceleration: 3.0
      linear.x.min_acceleration: -3.0
      linear.x.max_jerk: 5.0
      linear.x.min_jerk: -5.0

      linear.y.has_velocity_limits: false
      linear.y.has_acceleration_limits: true
      linear.y.has_jerk_limits: false
      linear.y.max_velocity: 2.0
      linear.y.min_velocity: -2.0
      linear.y.max_acceleration: 3.0
      linear.y.min_acceleration: -3.0
      linear.y.max_jerk: 5.0
      linear.y.min_jerk: -5.0
      
      angular.z.has_velocity_limits: false
      angular.z.has_acceleration_limits: true
      angular.z.has_jerk_limits: false
      angular.z.max_velocity: 3.0
      angular.z.min_velocity: -3.0
      angular.z.max_acceleration: 3.0
      angular.z.min_acceleration: -3.0
      angular.z.max_jerk: 5.0
      angular.z.min_jerk: -5.0
      


  forward_position_controller:
    ros__parameters:
      joints:
        - 'front_left_axle_joint'
        - 'front_right_axle_joint'
        - 'rear_left_axle_joint'
        - 'rear_right_axle_joint'
        - 'arm_roller_bar_joint'
        - 'elevator_outer_1_joint'
        - 'elevator_center_joint'
        - 'elevator_outer_2_joint'
        - 'top_slider_joint'
        - 'top_gripper_left_arm_joint'
        - 'top_gripper_right_arm_joint'
        - 'bottom_intake_joint'
        
  
  forward_velocity_controller:
    ros__parameters:
      joints:
      - 'front_left_wheel_joint'
      - 'front_right_wheel_joint'
      - 'rear_left_wheel_joint'
      - 'rear_right_wheel_joint'

      

  joint_trajectory_controller:
    ros__parameters:
      joints:
        - 'arm_roller_bar_joint'
        - 'elevator_center_joint'
        - 'elevator_outer_1_joint'
        - 'elevator_outer_2_joint'
        - 'top_gripper_right_arm_joint'
        - 'top_gripper_left_arm_joint'
        - 'top_slider_joint'
        - 'bottom_intake_joint'

      command_interfaces:
        - position

      state_interfaces:
        - position
        - velocity

      state_publish_rate: 50.0
      action_monitor_rate: 20.0

      allow_partial_joints_goal: false
      open_loop_control: true
      constraints:
        stopped_velocity_tolerance: 0.01
        goal_time: 0.0

