teleop_twist_joy_node:
  ros__parameters:
    require_enable_button: false
    axis_linear:  # Left thumb stick vertical
      x: 1
      y: 0
    scale_linear:
      x: 2.0
      y: 2.0
    scale_linear_turbo:
      x: 3.0
      y: 3.0

    axis_angular:  # Right thumb stick horizontal
      yaw: 3
    scale_angular:
      yaw: 2.0
    scale_angular_turbo:
      yaw: 3.0
    
    enable_turbo_button: 1
      
