#!/usr/bin/bash
scripts_dir=$( dirname "${BASH_SOURCE[0]}")
source $scripts_dir/nvidia_driver_config

docker run \
 --name isaac-sim \
 --entrypoint bash \
 -it --gpus all \
 --network=host \
 -e "ACCEPT_EULA=Y" \
 -v ${nvidia_layers}:/etc/vulkan/implicit_layer.d/nvidia_layers.json \
 -v ${nvidia_icd}:/etc/vulkan/icd.d/nvidia_icd.json \
 -v ${_10_nvidia}:/usr/share/glvnd/egl_vendor.d/10_nvidia.json \
 -v ${ISAAC_LOCAL_STORAGE}/cache/kit:/isaac-sim/kit/cache/Kit:rw \
 -v ${ISAAC_LOCAL_STORAGE}/cache/ov:/root/.cache/ov:rw \
 -v ${ISAAC_LOCAL_STORAGE}/cache/pip:/root/.cache/pip:rw \
 -v ${ISAAC_LOCAL_STORAGE}/cache/glcache:/root/.cache/nvidia/GLCache:rw \
 -v ${ISAAC_LOCAL_STORAGE}/cache/computecache:/root/.nv/ComputeCache:rw \
 -v ${ISAAC_LOCAL_STORAGE}/logs:/root/.nvidia-omniverse/logs:rw \
 -v ${ISAAC_LOCAL_STORAGE}/config:/root/.nvidia-omniverse/config:rw \
 -v ${ISAAC_LOCAL_STORAGE}/data:/root/.local/share/ov/data:rw \
 -v ${ISAAC_LOCAL_STORAGE}/documents:/root/Documents:rw \
 nvcr.io/nvidia/isaac-sim:2022.2.0