#!/usr/bin/bash

# mkdir -p ~/docker/isaac-sim/cache/kit
# mkdir -p ~/docker/isaac-sim/cache/ov
# mkdir -p ~/docker/isaac-sim/cache/pip
# mkdir -p ~/docker/isaac-sim/cache/glcache
# mkdir -p ~/docker/isaac-sim/cache/computecache
# mkdir -p ~/docker/isaac-sim/logs
# mkdir -p ~/docker/isaac-sim/logs-kit
# mkdir -p ~/docker/isaac-sim/config
# mkdir -p ~/docker/isaac-sim/data
# mkdir -p ~/docker/isaac-sim/documents

docker run \
 --name isaac-sim \
 --entrypoint bash \
 -it --rm --gpus all \
 --network=host \
 -e "ACCEPT_EULA=Y" \
 -v /etc/vulkan/icd.d/nvidia_icd.json:/etc/vulkan/icd.d/nvidia_icd.json \
 -v /etc/vulkan/implicit_layer.d/nvidia_layers.json:/etc/vulkan/implicit_layer.d/nvidia_layers.json \
 -v /usr/share/glvnd/egl_vendor.d/10_nvidia.json:/usr/share/glvnd/egl_vendor.d/10_nvidia.json \
 -v ~/docker/isaac-sim/cache/ov:/root/.cache/ov:rw \
 -v ~/docker/isaac-sim/cache/pip:/root/.cache/pip:rw \
 -v ~/docker/isaac-sim/cache/glcache:/root/.cache/nvidia/GLCache:rw \
 -v ~/docker/isaac-sim/cache/computecache:/root/.nv/ComputeCache:rw \
 -v ~/docker/isaac-sim/logs:/root/.nvidia-omniverse/logs:rw \
 -v ~/docker/isaac-sim/config:/root/.nvidia-omniverse/config:rw \
 -v ~/docker/isaac-sim/data:/root/.local/share/ov/data:rw \
 -v ~/docker/isaac-sim/documents:/root/Documents:rw \
 nvcr.io/nvidia/isaac-sim:2022.2.0