#!/bin/bash

# Check /scripts/config/remote-config for script configuration
source /workspaces/edna2023/scripts/config/remote-config


deploy-git() {
    echo "Deploying to $USERNAME@$IP_ADDRESS:$REMOTE_PATH via git..."
    if [[ ! $(git remote -v | grep $USERNAME@$IP_ADDRESS) ]]; then # Add it as a remote
            if [ $(git remote | grep "$MACHINE_NAME") ]; then # Remove the old jetson remote
                    git remote remove $MACHINE_NAME
            fi
            git remote add $MACHINE_NAME "$USERNAME@$IP_ADDRESS:$REMOTE_PATH"
    fi

    git push $MACHINE_NAME main
}

deploy-rsync() {
    echo "Deploying to $USERNAME@$IP_ADDRESS:$REMOTE_PATH via rsync..."
    rsync -azP --exclude build/ install/ log/ isaac/ .devcontainer/ docker/ /workspaces/edna2023/ $USERNAME@$IP_ADDRESS:$REMOTE_PATH
    echo "Connecting to $USERNAME@$IP_ADDRESS:$REMOTE_PATH and building..."
    ssh $USERNAME@$IP_ADDRESS "cd $REMOTE_PATH && source /opt/ros/humble/setup.bash && colcon build --symlink-install --paths src/* && sudo systemctl restart edna.service"
}

log() {
    echo "Checking edna.service status..."
    ssh $USERNAME@$IP_ADDRESS 'sudo systemctl status edna.service'
}

help() {
    echo "Usage:"
    echo "  config  -- Opens the config file in nano"
    echo "  setup   -- Copies your ssh-key to the remote device"
    echo "  ssh     -- Connects to the robot via ssh"
    echo "  connect -- alias for ssh"
    echo "  deploy"
    echo "      rsync   -- Deploys to the remote device using rsync (default)"
    echo "      git     -- Deploys to the remote device using Git"
    echo "Usage: remote (config | setup | deploy | log) [remote-username] [ip-address] [remote-path] [machine-name]"
}

case $1 in 
    "config")
        nano /workspaces/edna2023/scripts/config/pi-config
    ;;

    "setup")
        echo "Copying public key to $USERNAME@$IP_ADDRESS..."
        ssh-copy-id -i ~/.ssh/id_rsa.pub $USERNAME@$IP_ADDRESS
    ;;
        
    "connect") ;&
    "ssh")
        echo "Connecting to $USERNAME@$IP_ADDRESS"
        ssh $USERNAME@$IP_ADDRESS
    ;;

    "deploy")
        case $2 in
            "") ;&
            "rsync")
                deploy-rsync
            ;;
            
            "git")
                deploy-git
            ;;

            *)
                echo "Unknown option: $2"
                help
            ;;
        esac
        ;;

    "rebuild")
        echo "Rebuilding at $USERNAME@$IP_ADDRESS:$REMOTE_PATH..."
        ;;
    
    "log")
        log
        ;;
    
    *)
        echo "Unknown option: $1"
        help
        ;;
esac